[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker/virt.lds",
    "-C", "code-model=medium",
]
#rustflags = "-C link-arg=-Tlinker/virt.lds -C code-model=medium"


runner = "qemu-system-riscv64 -machine virt -cpu rv64 -smp 1 -m 256M  -nographic -serial mon:stdio -bios default -kernel "
#runner = "qemu-system-riscv64 -s -S -machine virt -cpu rv64 -smp 1 -m 256M  -nographic -serial mon:stdio -bios default -kernel "

[env]
RUST_LOG="info,krat_os=info,krat_os::kheap=debug"